name: stats-py310
channels:
  - conda-forge
  - nodefaults
dependencies:
  - python==3.10
  - ipykernel==6.28.0
  - numba==0.59.1
  - pandas==2.2.2
  - scikit-learn==1.4.2
  - scipy==1.13.0
  - seaborn==0.13.2
  - statsmodels==0.14.1
  - numpy==1.26.4
  - ipywidgets==8.1.2