name: evcomx
channels:
    - defaults
    - conda-forge
dependencies:
    - numpy==1.26.4
    - lightning==2.2.2
    - pytorch
    - keras==3.3.3
    - python==3.9
    - ipykernel
    - sklearn==1.4.2
    - pip:
        - jax
        - jaxlib
